const snarkjs = require('snarkjs');
const fs = require('fs');
const path = require('path');

class SnarkjsService {
    constructor() {
        this.vKeyPath = path.join(__dirname, '../../verification_keys/verification_key.json');
    }

    /**
     * Verifies a SnarkJS Groth16 Proof
     * @param {Object} proof - The JSON proof generated by the client
     * @param {Array} publicSignals - The public signals (currentDate, certificateHash, nullifierHash)
     * @returns {Promise<Object>} - The verification result
     */
    async verifyProof(proof, publicSignals) {
        try {
            if (!fs.existsSync(this.vKeyPath)) {
                console.error("CRITICAL CONFIGURATION ERROR: Genuine ZK vKey not found!");
                return {
                    valid: false,
                    message: "Verification failed: ZK configuration is missing. Refusing to perform mock structural verification.",
                    verified_at: new Date().toISOString()
                };
            }

            const vKey = JSON.parse(fs.readFileSync(this.vKeyPath, 'utf8'));
            
            // snarkjs.groth16.verify(vkey, publicSignals, proof)
            const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);
            
            return {
                valid: isValid,
                message: isValid ? "Genuine Groth16 ZK Proof verified successfully" : "ZK Proof verification failed",
                verified_at: new Date().toISOString(),
                nullifierHash: publicSignals[0] // The first output signal is nullifierHash
            };
        } catch (e) {
            console.error("ZK Verification Error:", e);
            return {
                valid: false,
                message: `Verification error: ${e.message}`,
                verified_at: new Date().toISOString()
            };
        }
    }
}

module.exports = new SnarkjsService();
