import nacl from 'tweetnacl';
import util from 'tweetnacl-util';

/**
 * Encrypts an AES key (or any string) using the recipient's Curve25519 public key.
 * This uses nacl.box with an ephemeral keypair for the sender.
 * 
 * @param {string} payloadStr The string to encrypt (e.g. the AES key).
 * @param {string} recipientPublicKeyBase64 The recipient's Curve25519 public key in Base64.
 * @returns {string} The encrypted payload, encoded in Base64 (includes ephemeral public key, nonce, and ciphertext).
 */
export const encryptKeyWithX25519 = (payloadStr, recipientPublicKeyBase64) => {
    // Generate an ephemeral keypair for the sender
    const ephemeralKeyPair = nacl.box.keyPair();

    // Decode recipient public key
    const recipientPublicKey = util.decodeBase64(recipientPublicKeyBase64);

    // Create a random nonce
    const nonce = nacl.randomBytes(nacl.box.nonceLength);

    // Convert payload to Uint8Array
    const messageUint8 = util.decodeUTF8(payloadStr); // or createBuffer if binary, but we are encrypting a string (AES key generated by forge is a binary-encoded string, we need it as a byte array)

    // The AES key generated by forge.random.getBytesSync is a binary string. 
    // To properly encode it for tweetnacl, we need to convert each char to a byte.
    // However, if we change AES generation to be standard, we can just use UTF8.
    // Assuming payloadStr is a binary-encoded string from forge:
    const payloadBytes = new Uint8Array(payloadStr.length);
    for (let i = 0; i < payloadStr.length; i++) {
        payloadBytes[i] = payloadStr.charCodeAt(i);
    }

    // Encrypt the message
    const encryptedMessage = nacl.box(payloadBytes, nonce, recipientPublicKey, ephemeralKeyPair.secretKey);

    // Combine ephemeral public key, nonce, and encrypted message
    // Format: [ephemeralPublicKey (32 bytes)] + [nonce (24 bytes)] + [encryptedMessage]
    const combinedBytes = new Uint8Array(ephemeralKeyPair.publicKey.length + nonce.length + encryptedMessage.length);
    combinedBytes.set(ephemeralKeyPair.publicKey, 0);
    combinedBytes.set(nonce, ephemeralKeyPair.publicKey.length);
    combinedBytes.set(encryptedMessage, ephemeralKeyPair.publicKey.length + nonce.length);

    // Return as Base64 string
    return util.encodeBase64(combinedBytes);
};

/**
 * Decrypts an AES key (or any payload) using the user's Curve25519 private key.
 * 
 * @param {string} encryptedPayloadBase64 The combined encrypted payload in Base64.
 * @param {string} myPrivateKeyBase64 The user's Curve25519 private key in Base64.
 * @returns {string} The decrypted payload string (e.g. the AES key).
 */
export const decryptKeyWithX25519 = (encryptedPayloadBase64, myPrivateKeyBase64) => {
    // Decode inputs
    const combinedBytes = util.decodeBase64(encryptedPayloadBase64);
    const mySecretKey = util.decodeBase64(myPrivateKeyBase64);

    // Extract pieces
    const ephemeralPublicKeyLength = nacl.box.publicKeyLength;
    const nonceLength = nacl.box.nonceLength;

    if (combinedBytes.length < ephemeralPublicKeyLength + nonceLength + nacl.box.macLength) {
        throw new Error("Encrypted payload is too short or malformed");
    }

    const ephemeralPublicKey = combinedBytes.slice(0, ephemeralPublicKeyLength);
    const nonce = combinedBytes.slice(ephemeralPublicKeyLength, ephemeralPublicKeyLength + nonceLength);
    const encryptedMessage = combinedBytes.slice(ephemeralPublicKeyLength + nonceLength);

    // Decrypt
    const decryptedBytes = nacl.box.open(encryptedMessage, nonce, ephemeralPublicKey, mySecretKey);

    if (!decryptedBytes) {
        throw new Error("Decryption failed. Incorrect private key or corrupt data.");
    }

    // Convert back to string (matching the binary string format used by forge)
    let payloadStr = '';
    for (let i = 0; i < decryptedBytes.length; i++) {
        payloadStr += String.fromCharCode(decryptedBytes[i]);
    }

    return payloadStr;
};
